name: CI
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}
      - run: echo ${{ inputs.tag }}
      - run: git log
      - run: git tag
